// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const row: string;
export const controlLabel: string;
export const icon: string;
export const helpIcon: string;
export const controlContainer: string;
export const tooltip: string;
