// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const cardPreviewContainer: string;
export const cardImg: string;
export const oracle: string;
export const nameRow: string;
export const typeline: string;
export const power: string;
export const flavorText: string;
