// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const stack: string;
export const card: string;
export const startTop: string;
export const startMid: string;
export const startBot: string;
