// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const mtgSlider: string;
export const slider: string;
export const count: string;
export const disableIcon: string;
export const disabled: string;
